data <- read.csv2("household_power_consumption.txt", stringsAsFactors=FALSE)
data$DateTime = as.POSIXlt(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data$Date = as.Date(data$Date, "%d/%m/%Y")
subsetdata <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02", select=c("DateTime", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
subsetdata$Sub_metering_1 = as.numeric(subsetdata$Sub_metering_1)
subsetdata$Sub_metering_2 = as.numeric(subsetdata$Sub_metering_2)
subsetdata$Sub_metering_3 = as.numeric(subsetdata$Sub_metering_3)
png(filename = "plot3.png")
plot(subsetdata$DateTime, subsetdata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(subsetdata$DateTime, subsetdata$Sub_metering_2, col="red")
lines(subsetdata$DateTime, subsetdata$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
dev.off()