data <- read.csv2("household_power_consumption.txt", stringsAsFactors=FALSE)
data$datetime = as.POSIXlt(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data$Date = as.Date(data$Date, "%d/%m/%Y")
subsetdata <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02", select=c("datetime", "Global_active_power", "Voltage", "Global_reactive_power", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
subsetdata$Global_active_power = as.numeric(subsetdata$Global_active_power)
subsetdata$Voltage = as.numeric(subsetdata$Voltage)
subsetdata$Global_reactive_power = as.numeric(subsetdata$Global_reactive_power)
subsetdata$Sub_metering_1 = as.numeric(subsetdata$Sub_metering_1)
subsetdata$Sub_metering_2 = as.numeric(subsetdata$Sub_metering_2)
subsetdata$Sub_metering_3 = as.numeric(subsetdata$Sub_metering_3)
png(filename = "plot4.png")
par(mfrow=c(2,2))
with(subsetdata, plot(datetime, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(subsetdata, plot(datetime, Voltage, type="l"))
with(subsetdata, plot(datetime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
with(subsetdata, lines(datetime, Sub_metering_2, col="red"))
with(subsetdata, lines(datetime, Sub_metering_3, col="blue"))
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
with(subsetdata, plot(datetime, Global_reactive_power, type="l"))
dev.off()